### ISSUE TITLE
Playbook-specific xp trigger not showing

### ISSUE THREAD

**Issue by Chlikaflok** [justinross/foundryvtt-blades-in-the-dark#11]
In the xp triggers section of the sheet, only the "Beliefs, Heritage..." and the "Issues from Vice..." entries show up.
![image](https://user-images.githubusercontent.com/5597880/132257595-2346dba7-be10-4b1f-8ace-9accc6bf16ba.png)

**Comment by justinross** [comment]
Fixed with e85fd3bf43c68448630e113206a6fb64e122e756
