### ISSUE TITLE
Trying to empty the crew vault changes to 12 coin rather than 0.

### ISSUE THREAD

**Issue by Chlikaflok** [justinross/foundryvtt-blades-in-the-dark#18]
In the Crew sheet, if there is any coin in the vault and you click the 1 twice to empty it, the value rolls back to full (expressed as "null" in the resulting json), rather than uncheck the last coin. This is working fine in the "coins" section, and only affects the "vault" section.
![Vault](https://user-images.githubusercontent.com/5597880/132989280-71e0bab4-cf23-4bf0-bbde-05384a747f8b.gif)

**Comment by justinross** [comment]
Fixed in latest release. Thanks!
