### ISSUE TITLE
Incorrect initialization of Traumas

### ISSUE THREAD

**Issue by Galdormin** [justinross/foundryvtt-blades-in-the-dark#2]
![image](https://user-images.githubusercontent.com/76685550/129451769-37f15386-a27a-48a9-8b9d-48952ea34d7e.png)

This problem occurs when creating a new character (on a new or existing world). These "traumas" cannot be removed and it is not possible to add new ones. No errors appear in the logs.

**Comment by Galdormin** [comment]
I have found a solution that seems to fix the problem but I am not sure if it is the best solution.

In `blades.js`, `Hooks.on("createActor", ...)`.

I replaced
```js
await actor.update({"data.trauma.list" : []});
```
by
```js
let default_trauma = {"cold": false, "haunted": false, "obsessed": false, "paranoid": false, "reckless": false, "soft": false, "unstable": false, "vicious": false};
await actor.update({"data.trauma.list" : default_trauma});
```

**Comment by justinross** [comment]
I ended up rewriting the way I was handling trauma (which was far more complicated than it should have been), so this should be resolved. Thanks!
